### ISSUE TITLE
lazyvim setup?

### ISSUE THREAD

**Issue by BBennettChiba** [typed-rocks/ts-worksheet-neovim#3]
Could you provide instructions for lazyvim support?
`{
  "typed-rocks/ts-worksheet-neovim",
  config = function()
    local tsws = require('ts-worksheet')
    tsws.setup()
  end,
}
`

I'm guessing something like this but where should I put the cli?

**Comment by chwoerz** [comment]
There is an open PR. I will review it today and merge it 👍

**Comment by chwoerz** [comment]
@BBennettChiba The PR was just merged, so you can now use it with lazy.nvim. Thanks to @heilgar
